apiVersion: v1
data:
  debug: "false"
  environment: dev
  support_email: kalvis@example.com
kind: ConfigMap
metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}