apiVersion: v1
data:
  host: postgres
kind: ConfigMap
metadata:
  name: '{{ template "helm-guestbook.fullname" . }}-db-config'
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    test: {{ .Values.test }}
